### PR TITLE
Add support for writing parallel structured VTK formats (.pvti / .pvtr / .pvts)

### PR DESCRIPTION
**Pull request by corentin-dev**
Here is a PR to close issue https://github.com/jipolanco/WriteVTK.jl/issues/91

What was added : support for `PRectilinearGrid`, `PStructuredGrid` and  `PImageData`.

`WholeExtent` needs to be improved. I am tempted to suggest using `MPI` here, but it would add a dependency? Any idea about this?

### CODE REVIEW

**Comment by corentin-dev** [comment]
@amartinhuertas maybe you have some ideas on how to improve this PR?

**Comment by jipolanco** [comment]
Thanks! I'm not yet sure about the best solution for the WholeExtent issue, but I think it's best to avoid depending on MPI.

I guess one simple solution would be to ask the user to explicitly pass `extent` and `whole_extent` as keyword arguments of `pvtk_grid` when writing structured grids. In parallel jobs, as a user one would like to have control of that anyway. Note that `extent` is already accepted by `vtk_grid`, but is not really documented...

**Comment by jipolanco** [comment]
I think I got all structured formats working correctly.

For now the partitioning must be specified by passing an `extents` array, which contains the subdomains associated to each process. In MPI applications, each process must know what is the portion of the domain associated to all other processes. This may require some MPI communications before calling `pvtk_grid`.

I'm open to other ways of specifying the extents, but I'd prefer if we could avoid depending on MPI. If it's really worth it, we could try to support MPI via [Requires](https://github.com/JuliaPackaging/Requires.jl).

I'll try to add some examples to the documentation. BTW, one annoying thing about parallel structured grids in VTK is that subdomains *must* overlap, or otherwise VTK (or at least ParaView) complains when loading the files. I'll mention this in the documentation.

**Comment by corentin-dev** [comment]
Good, I hope my work helped a bit ;-)

I'll try to use it in a parallel, though I don't have overlap, so we will see how it is handled...

**Pull request merged**
