### PR TITLE
Allow unstructured grids with more than `typemax(Int32)` points

### LINKED ISSUE #105: Inexact Error: ran out of numbers
For a large mesh (840M tetrahedra), I got this error:
```
ERROR: LoadError: InexactError: trunc(Int32, 2147483648)
Stacktrace:
  [1] throw_inexacterror(f::Symbol, #unused#::Type{Int32}, val::Int64)
    @ Core ./boot.jl:612
  [2] checked_trunc_sint
    @ ./boot.jl:634 [inlined]
  [3] toInt32
    @ ./boot.jl:671 [inlined]
  [4] Int32
    @ ./boot.jl:761 [inlined]
  [5] convert
    @ ./number.jl:7 [inlined]
  [6] setindex!
    @ ./array.jl:903 [inlined]
  [7] add_cells!(vtk::WriteVTK.DatasetFile, xml_piece::LightXML.XMLElement, number_attr::String, xml_name::String, cells::Vector{WriteVTK.MeshCell{WriteVTK.VTKCellTypes.VTKCellType, SubArray{Int64, 1, Matrix{Int64}, Tuple{Int64, Base.Slice{Base.OneTo{Int64}}}, true}}}; with_types::Val{true})
    @ WriteVTK ~/.julia/packages/WriteVTK/nNSYd/src/gridtypes/unstructured/unstructured.jl:92
  [8] add_cells!
    @ ~/.julia/packages/WriteVTK/nNSYd/src/gridtypes/unstructured/unstructured.jl:67 [inlined]
  [9] vtk_grid(dtype::WriteVTK.VTKUnstructuredGrid, filename::String, points::Matrix{Float64}, cells::Vector{WriteVTK.MeshCell{WriteVTK.VTKCellTypes.VTKCellType, SubArray{Int64, 1, Matrix{Int64}, Tuple{Int64, Base.Slice{Base.OneTo{Int64}}}, true}}}; kwargs::Base.Pairs{Symbol, Int64, Tuple{Symbol}, NamedTuple{(:compress,), Tuple{Int64}}})
    @ WriteVTK ~/.julia/packages/WriteVTK/nNSYd/src/gridtypes/unstructured/unstructured.jl:196
 [10] vtk_grid(::String, ::Matrix{Float64}, ::Vector{WriteVTK.MeshCell{WriteVTK.VTKCellTypes.VTKCellType, SubArray{Int64, 1, Matrix{Int64}, Tuple{Int64, Base.Slice{Base.OneTo{Int64}}}, true}}}; kwargs::Base.Pairs{Symbol, Int64, Tuple{Symbol}, NamedTuple{(:compress,), Tuple{Int64}}})
    @ WriteVTK ~/.julia/packages/WriteVTK/nNSYd/src/gridtypes/unstructured/unstructured.jl:220
 [11] vtkwrite(theFile::String, Connectivity::Matrix{Int64}, Points::Matrix{Float64}, celltype::WriteVTK.VTKCellTypes.VTKCellType; vectors::Nothing, scalars::Nothing)
    @ FinEtools.MeshExportModule.VTKWrite ~/.julia/packages/FinEtools/4aVZc/src/MeshExportModule.jl:1426
 [12] vtkwrite
    @ ~/.julia/packages/FinEtools/4aVZc/src/MeshExportModule.jl:1412 [inlined]
 [13] vtkwrite(theFile::String, fens::FENodeSet, fes::FESetT4; opts::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
```
It is apparently due to the `offsets` being created as `Int32`. Is this required by 
the file format? Could this be changed to `Int64`?

### PR DESCRIPTION
**Pull request by jipolanco**
Fixes #105

### CODE REVIEW

**Comment by PetrKryslUCSD** [comment]
Seems to be working! Many thanks!

**Comment by jipolanco** [comment]
> Is it possible to support both depending on the input connectivity type?

Yes, that would make sense. I can't look at this right now, but I should be able to add this within the next couple of weeks.

**Comment by jipolanco** [comment]
@henry2004y this should be now fixed by #107 (v1.14.4).

**Comment by henry2004y** [comment]
Great! Thank you!

**Pull request merged**
