### PR TITLE
Add VTKCellType as a new type to allow for error checking

### PR DESCRIPTION
**Pull request by fredrikekre**
Introduces the `VTKCellType` which holds the `vtk_name` and `vtk_id` number as well as the number of nodes (if applicable for the celltype, some celltypes can have arbitrary size, hence the -1 on them).

This is used to check the input length of the connectivity vector when creating a `MeshCell`.

Also, this is potentially breaking some code since the `VTKCellType` module is renamed to `VTKCellTypes`.

WIP since the number of nodes are not specified for all types yet.

### CODE REVIEW

**Comment by jipolanco** [comment]
Hi Fredrik, thanks for your contribution! I like the idea of defining `VTKCellType` as an immutable type and checking the number of indices in the connectivity vector.

I would just prefer not to break compatibility with previous versions of the package. That's why I propose to rename the new immutable type to something else (maybe just `CellType`, it doesn't matter too much since the type name is not exported and is generally not visible to the user), and keep `VTKCellType` as the name of the module. I'll take care of those small changes and merge your code.

**Comment by fredrikekre** [comment]
Okay, I will update and push.

I just liked the idea of the module which defines `VTKCellType` to be named `VTKCellTypes`, as is common in julia packages. I was thinking about some way to include some deprecation to warn the user but still redirect it so that old code is still functional.

It is possible to define something like `const VTKCellType = VTKCellTypes` which allows for the old code to run. Would that be a good solution? It doesn't give a warning though...

Ideally I would like to produce something like this

```
c = VTKCellType.VTK_TRIANGLE
WARNING: The VTKCellType module is renamed, use VTKCellTypes instead.

```

**Comment by jipolanco** [comment]
I agree that your naming scheme makes more sense. That sounds good to me, you can define the module `VTKCellTypes` and then set `const VTKCellType = VTKCellTypes`.

However I don't really know how to get a warning when using `VTKCellType`. I tested with the `@deprecate_binding` macro in julia 0.5 (defined [here](https://github.com/JuliaLang/julia/blob/8761c48f8497710f572c18f39e83a7b3fc1ceadc/base/deprecated.jl#L100)) like this:
```
module VTKCellTypes
...
end

Base.@deprecate_binding VTKCellType VTKCellTypes
```
which leads to warnings that look like this:
```
WARNING: WriteVTK.VTKCellType is deprecated.
  likely near [...]/WriteVTK/test/unstructured.jl:84
```
The problem is that this warning is not clear enough, since it doesn't tell the user to use `VTKCellTypes` instead... Maybe by defining a custom version of `@deprecate_binding` we can get a more descriptive warning.

**Comment by fredrikekre** [comment]
I tried to make a custom macro, but the deprecate binding macro seems to be in a c function. Will leave it like this now, using VTKCellType works with this.

Might try to get a deprecation warning some time later. At least this works with both new and old way.

**Comment by fredrikekre** [comment]
See JuliaLang/julia#18392

**Comment by jipolanco** [comment]
Thanks, this is great. I don't think the warning problem is a big deal, we can leave it as it is and people will eventually start using `VTKCellTypes` instead of `VTKCellType`. And if the PR you made to modify `@deprecate_binding` is merged, we can then use that macro as well (by the way nice work there!).

**Pull request merged**
