### PR TITLE
Support for 1D and 2D input

### PR DESCRIPTION
**Pull request by fredrikekre**
See #19 , ~~this is still work in progress.~~

- [x] 1D/2D unstructured grid
- [x]  ~~1D~~/2D structured grid
- [x]  ~~1D~~/2D rectilinear grid
- [x] Documentation
- [x] Tests

### CODE REVIEW

**Comment by jipolanco** [comment]
Ok great, I'll take a look later when I have some time!

**Comment by fredrikekre** [comment]
Sorry about that. i just let my spellchecker change and didn't think more about it.

**Comment by fredrikekre** [comment]
Also, this should close #12

**Comment by jipolanco** [comment]
Don't worry. Thanks a lot for the PR!

**Comment by fredrikekre** [comment]
Sorry for all the noise, but could a new version be tagged? :)

**Comment by jipolanco** [comment]
I tried to tag v0.4.0, but I'm having problems with the PkgDev.publish() function under Julia 0.5. It seems to be related to [this issue](https://github.com/JuliaLang/PkgDev.jl/issues/69). I'll try to publish the new version using Julia 0.4.

**Comment by KristofferC** [comment]
You can also manually push the commit to a local METADATA and create a pull request from there.

**Pull request merged**
